[package]
name = "hbase-thrift"
version = "0.1.0"
edition = "2021"
licence = "MIT OR Apache-2.0"
description = "An HBase client via Thrift"
repository = "https://github.com/midnightexigent/hbase-thrift-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.14"
thiserror = "1.0.30"
thrift = "0.15.0"

[features]
