[package]
name = "hbase-thrift"
version = "0.6.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/midnightexigent/hbase-thrift-rs"
description = "A client for HBase's Thrift Interface"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
easy-ext = "1.0.0"
thiserror = "1.0.30"
thrift = "0.15.0"

[features]
